### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by nickoliasxii** [matlittle/project-2-group-2#6]
## Age Verification (Enter Birthdate) ->

* Separated into categories: 13-17 or 18+ ->
- Besides differences in questions and results, it's essentially the same after this

## Three Account Creation Options
- Either make an account before you begin or after you finish
- Require an account to be created before they begin the questionnaire
- Only ask if the user would like to create an account once they receive their results/resources

**Comment by matlittle** [comment]
PR #16 adds the basic login functionality. We can decide when we want to prompt for account creation as we move forward.
